# Generated by Django 2.1.2 on 2018-10-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='mobile_number',
            field=models.CharField(max_length=200, verbose_name='mobile_number'),
        ),
    ]
