# Generated by Django 2.1a1 on 2018-11-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, verbose_name='serial_number')),
                ('email_address', models.EmailField(max_length=200, verbose_name='email_address')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
            ],
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('On-Leave', 'On-Leave'), ('Retired', 'Retired'), ('Dead', 'Dead')], default='Working', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='city',
            field=models.CharField(choices=[('Alaminos', 'Alaminos'), ('Angeles', 'Angeles'), ('Antipolo', 'Antipolo'), ('Bacolod', 'Bacolod'), ('Bacoor', 'Bacoor'), ('Bago', 'Bago'), ('Baguio', 'Baguio'), ('Bais', 'Bais'), ('Balanga', 'Balanga'), ('Batac', 'Batac'), ('Batangas', 'Batangas'), ('Bayawan', 'Bayawan'), ('Baybay', 'Baybay'), ('Bayugan', 'Bayugan'), ('Biñan', 'Biñan'), ('Bislig', 'Bislig'), ('Bogo', 'Bogo'), ('Borongan', 'Borongan'), ('Butuan', 'Butuan'), ('Cabadbaran', 'Cabadbaran'), ('Cabanatuan', 'Cabanatuan'), ('Cabuyao', 'Cabuyao'), ('Cadiz', 'Cadiz'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Calamba', 'Calamba'), ('Calapan', 'Calapan'), ('Calbayog', 'Calbayog'), ('Caloocan', 'Caloocan'), ('Candon', 'Candon'), ('Canlaon', 'Canlaon'), ('Carcar', 'Carcar'), ('Catbalogan', 'Catbalogan'), ('Cauayan', 'Cauayan'), ('Cavite', 'Cavite'), ('Cebu', 'Cebu'), ('Cotabato', 'Cotabato'), ('Dagupan', 'Dagupan'), ('Danao', 'Danao'), ('Dapitan', 'Dapitan'), ('Dasmariñas', 'Dasmariñas'), ('Davao', 'Davao'), ('Digos', 'Digos'), ('Dipolog', 'Dipolog'), ('Dumaguete', 'Dumaguete'), ('El Salvador', 'El Salvador'), ('Escalante', 'Escalante'), ('Gapan', 'Gapan'), ('General Santos', 'General Santos'), ('General Trias', 'General Trias'), ('Gingoog', 'Gingoog'), ('Guihulngan', 'Guihulngan'), ('Himamaylan', 'Himamaylan'), ('Ilagan', 'Ilagan'), ('Iligan', 'Iligan'), ('Iloilo', 'Iloilo'), ('Imus', 'Imus'), ('Iriga', 'Iriga'), ('Isabela', 'Isabela'), ('Kabankalan', 'Kabankalan'), ('Kidapawan', 'Kidapawan'), ('Koronadal', 'Koronadal'), ('La Carlota', 'La Carlota'), ('Lamitan', 'Lamitan'), ('Laoag', 'Laoag'), ('Lapu‑Lapu', 'Lapu‑Lapu'), ('Las Piñas', 'Las Piñas'), ('Legazpi', 'Legazpi'), ('Ligao', 'Ligao'), ('Lipa', 'Lipa'), ('Lucena', 'Lucena'), ('Maasin', 'Maasin'), ('Mabalacat', 'Mabalacat'), ('Makati', 'Makati'), ('Malabon', 'Malabon'), ('Malaybalay', 'Malaybalay'), ('Malolos', 'Malolos'), ('Mandaluyong', 'Mandaluyong'), ('Mandaue', 'Mandaue'), ('Manila', 'Manila'), ('Marawi', 'Marawi'), ('Marikina', 'Marikina'), ('Masbate', 'Masbate'), ('Mati', 'Mati'), ('Meycauayan', 'Meycauayan'), ('Muñoz', 'Muñoz'), ('Muntinlupa', 'Muntinlupa'), ('Naga - Camarines Sur', 'Naga - Camarines Sur'), ('Naga - Cebu', 'Naga - Cebu'), ('Navotas', 'Navotas'), ('Olongapo', 'Olongapo'), ('Ormoc', 'Ormoc'), ('Oroquieta', 'Oroquieta'), ('Ozamiz', 'Ozamiz'), ('Pagadian', 'Pagadian'), ('Palayan', 'Palayan'), ('Panabo', 'Panabo'), ('Parañaque', 'Parañaque'), ('Pasay', 'Pasay'), ('Pasig', 'Pasig'), ('Passi', 'Passi'), ('Puerto Princesa', 'Puerto Princesa'), ('Quezon', 'Quezon'), ('Roxas', 'Roxas'), ('Sagay', 'Sagay'), ('Samal', 'Samal'), ('San Carlos - Negros Occidental', 'San Carlos - Negros Occidental'), ('San Carlos - Pangasinan', 'San Carlos - Pangasinan'), ('San Fernando - La Union', 'San Fernando - La Union'), ('San Fernando - Pampanga', 'San Fernando - Pampanga'), ('San Jose', 'San Jose'), ('San Jose del Monte', 'San Jose del Monte'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('San Pedro', 'San Pedro'), ('Santa Rosa', 'Santa Rosa'), ('Santiago', 'Santiago'), ('Silay', 'Silay'), ('Sipalay', 'Sipalay'), ('Sorsogon', 'Sorsogon'), ('Surigao', 'Surigao'), ('Tabaco', 'Tabaco'), ('Tabuk', 'Tabuk'), ('Tacloban', 'Tacloban'), ('Tacurong', 'Tacurong'), ('Tagaytay', 'Tagaytay'), ('Tagbilaran', 'Tagbilaran'), ('Taguig', 'Taguig'), ('Tagum', 'Tagum'), ('Talisay - Cebu', 'Talisay - Cebu'), ('Talisay - Negros Occidental', 'Talisay - Negros Occidental'), ('Tanauan', 'Tanauan'), ('Tandag', 'Tandag'), ('Tangub', 'Tangub'), ('Tanjay', 'Tanjay'), ('Tarlac', 'Tarlac'), ('Tayabas', 'Tayabas'), ('Toledo', 'Toledo'), ('Trece Martires', 'Trece Martires'), ('Tuguegarao', 'Tuguegarao'), ('Urdaneta', 'Urdaneta'), ('Valencia', 'Valencia'), ('Valenzuela', 'Valenzuela'), ('Victorias', 'Victorias'), ('Vigan', 'Vigan'), ('Zamboanga', 'Zamboanga')], default='None', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='account',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User'),
        ),
    ]
