# Generated by Django 2.1.2 on 2018-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('FOU NCR-CL', 'FOU NCR-CL'), ('FOU NWLZN', 'FOU NWLZN'), ('FOU NELZN', 'FOU NELZN'), ('FOU SOUTHERN TAG', 'FOU SOUTHERN TAG'), ('FOU BICOL', 'FOU BICOL'), ('FOU PALAWAN', 'FOU PALAWAN'), ('FOU CENTRAL VISAYAS', 'FOU CENTRAL VISAYAS'), ('FOU EASTERN VISAYAS', 'FOU EASTERN VISAYAS'), ('FOU WESTERN VISAYAS', 'FOU WESTERN VISAYAS'), ('FOU SWM', 'FOU SWM'), ('FOU SEM', 'FOU SEM'), ('FOU NM', 'FOU NM'), ('FOU SV(DUMAGUETE)', 'FOU SV(DUMAGUETE)')], default='None', max_length=100, verbose_name='area')),
                ('team', models.CharField(max_length=500, verbose_name='team')),
                ('handlers', models.IntegerField(default='None', verbose_name='handlers')),
                ('EDD', models.IntegerField(default='None', verbose_name='EDD')),
                ('NDD', models.IntegerField(default='None', verbose_name='NDD')),
                ('SAR', models.IntegerField(default='None', verbose_name='SAR')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Alaminos', 'Alaminos'), ('Angeles', 'Angeles'), ('Antipolo', 'Antipolo'), ('Bacolod', 'Bacolod'), ('Bacoor', 'Bacoor'), ('Bago', 'Bago'), ('Baguio', 'Baguio'), ('Bais', 'Bais'), ('Balanga', 'Balanga'), ('Batac', 'Batac'), ('Batangas', 'Batangas'), ('Bayawan', 'Bayawan'), ('Baybay', 'Baybay'), ('Bayugan', 'Bayugan'), ('Biñan', 'Biñan'), ('Bislig', 'Bislig'), ('Bogo', 'Bogo'), ('Borongan', 'Borongan'), ('Butuan', 'Butuan'), ('Cabadbaran', 'Cabadbaran'), ('Cabanatuan', 'Cabanatuan'), ('Cabuyao', 'Cabuyao'), ('Cadiz', 'Cadiz'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Calamba', 'Calamba'), ('Calapan', 'Calapan'), ('Calbayog', 'Calbayog'), ('Caloocan', 'Caloocan'), ('Candon', 'Candon'), ('Canlaon', 'Canlaon'), ('Carcar', 'Carcar'), ('Catbalogan', 'Catbalogan'), ('Cauayan', 'Cauayan'), ('Cavite', 'Cavite'), ('Cebu', 'Cebu'), ('Cotabato', 'Cotabato'), ('Dagupan', 'Dagupan'), ('Danao', 'Danao'), ('Dapitan', 'Dapitan'), ('Dasmariñas', 'Dasmariñas'), ('Davao', 'Davao'), ('Digos', 'Digos'), ('Dipolog', 'Dipolog'), ('Dumaguete', 'Dumaguete'), ('El Salvador', 'El Salvador'), ('Escalante', 'Escalante'), ('Gapan', 'Gapan'), ('General Santos', 'General Santos'), ('General Trias', 'General Trias'), ('Gingoog', 'Gingoog'), ('Guihulngan', 'Guihulngan'), ('Himamaylan', 'Himamaylan'), ('Ilagan', 'Ilagan'), ('Iligan', 'Iligan'), ('Iloilo', 'Iloilo'), ('Imus', 'Imus'), ('Iriga', 'Iriga'), ('Isabela', 'Isabela'), ('Kabankalan', 'Kabankalan'), ('Kidapawan', 'Kidapawan'), ('Koronadal', 'Koronadal'), ('La Carlota', 'La Carlota'), ('Lamitan', 'Lamitan'), ('Laoag', 'Laoag'), ('Lapu‑Lapu', 'Lapu‑Lapu'), ('Las Piñas', 'Las Piñas'), ('Legazpi', 'Legazpi'), ('Ligao', 'Ligao'), ('Lipa', 'Lipa'), ('Lucena', 'Lucena'), ('Maasin', 'Maasin'), ('Mabalacat', 'Mabalacat'), ('Makati', 'Makati'), ('Malabon', 'Malabon'), ('Malaybalay', 'Malaybalay'), ('Malolos', 'Malolos'), ('Mandaluyong', 'Mandaluyong'), ('Mandaue', 'Mandaue'), ('Manila', 'Manila'), ('Marawi', 'Marawi'), ('Marikina', 'Marikina'), ('Masbate', 'Masbate'), ('Mati', 'Mati'), ('Meycauayan', 'Meycauayan'), ('Muñoz', 'Muñoz'), ('Muntinlupa', 'Muntinlupa'), ('Naga - Camarines Sur', 'Naga - Camarines Sur'), ('Naga - Cebu', 'Naga - Cebu'), ('Navotas', 'Navotas'), ('Olongapo', 'Olongapo'), ('Ormoc', 'Ormoc'), ('Oroquieta', 'Oroquieta'), ('Ozamiz', 'Ozamiz'), ('Pagadian', 'Pagadian'), ('Palayan', 'Palayan'), ('Panabo', 'Panabo'), ('Parañaque', 'Parañaque'), ('Pasay', 'Pasay'), ('Pasig', 'Pasig'), ('Passi', 'Passi'), ('Puerto Princesa', 'Puerto Princesa'), ('Quezon', 'Quezon'), ('Roxas', 'Roxas'), ('Sagay', 'Sagay'), ('Samal', 'Samal'), ('San Carlos - Negros Occidental', 'San Carlos - Negros Occidental'), ('San Carlos - Pangasinan', 'San Carlos - Pangasinan'), ('San Fernando - La Union', 'San Fernando - La Union'), ('San Fernando - Pampanga', 'San Fernando - Pampanga'), ('San Jose', 'San Jose'), ('San Jose del Monte', 'San Jose del Monte'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('San Pedro', 'San Pedro'), ('Santa Rosa', 'Santa Rosa'), ('Santiago', 'Santiago'), ('Silay', 'Silay'), ('Sipalay', 'Sipalay'), ('Sorsogon', 'Sorsogon'), ('Surigao', 'Surigao'), ('Tabaco', 'Tabaco'), ('Tabuk', 'Tabuk'), ('Tacloban', 'Tacloban'), ('Tacurong', 'Tacurong'), ('Tagaytay', 'Tagaytay'), ('Tagbilaran', 'Tagbilaran'), ('Taguig', 'Taguig'), ('Tagum', 'Tagum'), ('Talisay - Cebu', 'Talisay - Cebu'), ('Talisay - Negros Occidental', 'Talisay - Negros Occidental'), ('Tanauan', 'Tanauan'), ('Tandag', 'Tandag'), ('Tangub', 'Tangub'), ('Tanjay', 'Tanjay'), ('Tarlac', 'Tarlac'), ('Tayabas', 'Tayabas'), ('Toledo', 'Toledo'), ('Trece Martires', 'Trece Martires'), ('Tuguegarao', 'Tuguegarao'), ('Urdaneta', 'Urdaneta'), ('Valencia', 'Valencia'), ('Valenzuela', 'Valenzuela'), ('Victorias', 'Victorias'), ('Vigan', 'Vigan'), ('Zamboanga', 'Zamboanga')], default='None', max_length=100, verbose_name='city')),
                ('zip_code', models.IntegerField(verbose_name='zip_code')),
                ('address', models.CharField(default='None', max_length=500, verbose_name='address')),
            ],
        ),
    ]
