# Generated by Django 2.1a1 on 2019-01-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0001_initial'),
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K9_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='date_start')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='date_end')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
    ]
