# Generated by Django 2.1.2 on 2018-10-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOU NCR-CL', 'FOU NCR-CL'), ('FOU NWLZN', 'FOU NWLZN'), ('FOU NELZN', 'FOU NELZN'), ('FOU SOUTHERN TAG', 'FOU SOUTHERN TAG'), ('FOU BICOL', 'FOU BICOL'), ('FOU PALAWAN', 'FOU PALAWAN'), ('FOU CENTRAL VISAYAS', 'FOU CENTRAL VISAYAS'), ('FOU EASTERN VISAYAS', 'FOU EASTERN VISAYAS'), ('FOU WESTERN VISAYAS', 'FOU WESTERN VISAYAS'), ('FOU SWM', 'FOU SWM'), ('FOU SEM', 'FOU SEM'), ('FOU NM', 'FOU NM'), ('FOU SV(DUMAGUETE)', 'FOU SV(DUMAGUETE)')], default='None', max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team', max_length=500, verbose_name='name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handlers', models.IntegerField(default=0, verbose_name='handlers')),
                ('EDD', models.IntegerField(default=0, verbose_name='EDD')),
                ('NDD', models.IntegerField(default=0, verbose_name='NDD')),
                ('SAR', models.IntegerField(default=0, verbose_name='SAR')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Area')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Team')),
            ],
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
