# Generated by Django 2.1a1 on 2019-02-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.DecimalField(decimal_places=4, max_digits=50, null=True, verbose_name='longtitude')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=50, null=True, verbose_name='latitude')),
                ('dog_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Dog_Request')),
            ],
        ),
    ]
