# Generated by Django 2.1a1 on 2019-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_request_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='k9_schedule',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='duration'),
        ),
    ]
