# Generated by Django 2.1a1 on 2019-01-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_k9_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='k9_schedule',
            name='dog_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Dog_Request'),
        ),
    ]
