# Generated by Django 2.1.2 on 2018-10-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20181025_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
    ]
