# Generated by Django 2.1a1 on 2019-02-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_k9_schedule_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k9_schedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='dog_request',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='duration'),
        ),
    ]
