# Generated by Django 2.1a1 on 2018-11-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0003_auto_20181122_2125'),
        ('deployment', '0003_auto_20181027_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=100, verbose_name='requester')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='phone_number')),
                ('email_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='remarks')),
                ('EDD_needed', models.IntegerField(default=0, verbose_name='EDD_needed')),
                ('NDD_needed', models.IntegerField(default=0, verbose_name='NDD_needed')),
                ('SAR_needed', models.IntegerField(default=0, verbose_name='SAR_needed')),
                ('EDD_deployed', models.IntegerField(default=0, verbose_name='EDD_deployed')),
                ('NDD_deployed', models.IntegerField(default=0, verbose_name='NDD_deployed')),
                ('SAR_deployed', models.IntegerField(default=0, verbose_name='SAR_deployed')),
                ('total_dogs_demand', models.IntegerField(default=0, verbose_name='total_dogs_demand')),
                ('total_dogs_deployed', models.IntegerField(default=0, verbose_name='total_dogs_deployed')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('status', models.CharField(default='Pending', max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Dog_Deployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Deployed', max_length=100, null=True, verbose_name='status')),
                ('date_added', models.DateField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('date_pulled', models.DateField(blank=True, null=True, verbose_name='date_pulled')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='area',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='team_assignment',
            name='EDD',
        ),
        migrations.RemoveField(
            model_name='team_assignment',
            name='NDD',
        ),
        migrations.RemoveField(
            model_name='team_assignment',
            name='SAR',
        ),
        migrations.RemoveField(
            model_name='team_assignment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='team_assignment',
            name='handlers',
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Area'),
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(default='Undefined', max_length=100, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(default='unassigned', max_length=100, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='EDD_demand',
            field=models.IntegerField(default=0, verbose_name='EDD_demand'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='EDD_deployed',
            field=models.IntegerField(default=0, verbose_name='EDD_deployed'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='NDD_demand',
            field=models.IntegerField(default=0, verbose_name='NDD_demand'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='NDD_deployed',
            field=models.IntegerField(default=0, verbose_name='NDD_deployed'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='SAR_demand',
            field=models.IntegerField(default=0, verbose_name='SAR_demand'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='SAR_deployed',
            field=models.IntegerField(default=0, verbose_name='SAR_deployed'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date_added'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Location'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='total_dogs_demand',
            field=models.IntegerField(default=0, verbose_name='total_dogs_demand'),
        ),
        migrations.AddField(
            model_name='team_assignment',
            name='total_dogs_deployed',
            field=models.IntegerField(default=0, verbose_name='total_dogs_deployed'),
        ),
        migrations.AlterField(
            model_name='team_assignment',
            name='team',
            field=models.CharField(max_length=100, verbose_name='team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='team_dog_deployed',
            name='team_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Team_Assignment'),
        ),
        migrations.AddField(
            model_name='team_dog_deployed',
            name='team_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Dog_Request'),
        ),
        migrations.AddField(
            model_name='dog_request',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Location'),
        ),
    ]
