# Generated by Django 2.1a1 on 2019-01-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_incidents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='date',
        ),
        migrations.AddField(
            model_name='incidents',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_time'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='type',
            field=models.CharField(choices=[('Bomb Related', 'Bomb Related'), ('Drug Related', 'Drug Related'), ('Search and Rescue Related', 'Search and Rescue Related'), ('Others', 'Others')], default='Others', max_length=100, verbose_name='type'),
        ),
    ]
