# Generated by Django 2.1a1 on 2019-02-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_auto_20190228_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_coordinates',
            name='dog_request',
        ),
        migrations.AddField(
            model_name='dog_request',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployment.Request_Coordinates'),
        ),
    ]
