# Generated by Django 2.1a1 on 2019-02-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20190228_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_request',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Area'),
        ),
    ]
