# Generated by Django 2.1a1 on 2019-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0006_auto_20190131_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='type',
            field=models.CharField(choices=[('Explosives Related', 'Explosives Related'), ('Narcotics Related', 'Narcotics Related'), ('Search and Rescue Related', 'Search and Rescue Related'), ('Others', 'Others')], default='Others', max_length=100, verbose_name='type'),
        ),
    ]
