# Generated by Django 2.1a1 on 2019-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0007_auto_20190206_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_request',
            name='phone_number',
            field=models.CharField(default='n/a', max_length=100, verbose_name='phone_number'),
        ),
    ]
