# Generated by Django 2.1a1 on 2019-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0008_auto_20190228_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=50, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longtitude',
            field=models.DecimalField(decimal_places=4, max_digits=50, null=True, verbose_name='longtitude'),
        ),
    ]
