# Generated by Django 2.1.2 on 2018-10-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('foodtype', models.CharField(choices=[('Adult Dog Food', 'Adult Dog Food'), ('Puppy Dog Food', 'Puppy Dog Food'), ('Both', 'Both')], max_length=50, verbose_name='foodtype')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('dose', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='dose')),
                ('uom', models.CharField(choices=[('mg', 'mg'), ('mL', 'mL')], default='mg', max_length=10, verbose_name='uom')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_fullname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscellaneous', models.CharField(max_length=100)),
                ('uom', models.CharField(choices=[('pc', 'pc'), ('pack', 'pack'), ('box', 'box'), ('roll', 'roll'), ('can', 'can'), ('bottle', 'bottle'), ('tube', 'tube')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('miscellaneous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
            ],
        ),
    ]
