
# Generated by Django 2.1a1 on 2018-11-23 05:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('profiles', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='DamagedEquipemnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('concern', models.CharField(choices=[('Broken', 'Broken'), ('Lost', 'Lost'), ('Stolen', 'Stolen')], max_length=100, verbose_name='concern')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('foodtype', models.CharField(choices=[('Adult Dog Food', 'Adult Dog Food'), ('Puppy Dog Food', 'Puppy Dog Food')], max_length=50, verbose_name='foodtype')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('med_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Bottle', 'Bottle'), ('Vaccine', 'Vaccine')], default='Drug', max_length=50, verbose_name='med_type')),
                ('dose', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='dose')),
                ('uom', models.CharField(blank=True, default='unit', max_length=10, null=True, verbose_name='uom')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price')),
                ('used_yearly', models.IntegerField(default=0, verbose_name='used_yearly')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('medicine_fullname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration_date')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscellaneous', models.CharField(max_length=100)),
                ('uom', models.CharField(choices=[('pc', 'pc'), ('pack', 'pack'), ('box', 'box'), ('roll', 'roll'), ('can', 'can'), ('bottle', 'bottle'), ('tube', 'tube')], default='pack', max_length=100)),
                ('misc_type', models.CharField(choices=[('Equipment', 'Equipment'), ('Vet Supply', 'Vet Supply'), ('Others', 'Others')], default='Equipment', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('miscellaneous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Inventory_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_counted', models.DateField(auto_now_add=True, verbose_name='date_counted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.AddField(
            model_name='damagedequipemnt',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous'),
        ),
        migrations.AddField(
            model_name='damagedequipemnt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User'),
        ),
    ]
