# Generated by Django 2.1.2 on 2018-10-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedEquipemnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('concern', models.CharField(choices=[('Broken', 'Broken'), ('Lost', 'Lost'), ('Stolen', 'Stolen')], max_length=100, verbose_name='concern')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='misc_type',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Vet Supply', 'Vet Supply'), ('Others', 'Others')], default='Equipment', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine_subtracted_trail',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine_subtracted_trail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='uom',
            field=models.CharField(choices=[('pc', 'pc'), ('pack', 'pack'), ('box', 'box'), ('roll', 'roll'), ('can', 'can'), ('bottle', 'bottle'), ('tube', 'tube')], default='pack', max_length=100),
        ),
        migrations.AddField(
            model_name='damagedequipemnt',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous'),
        ),
    ]
