# Generated by Django 2.1.2 on 2018-10-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Food_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Received_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='date_received')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous_Subtracted_Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_subtracted', models.DateField(auto_now_add=True, verbose_name='date_subtracted')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='time')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous_Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_type',
            field=models.CharField(choices=[('Drug', 'Drug'), ('Vaccine', 'Vaccine')], default='Drug', max_length=50, verbose_name='med_type'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='price'),
        ),
    ]
