# Generated by Django 2.1a1 on 2018-10-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
