# Generated by Django 2.1.2 on 2018-10-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('problem', models.TextField(max_length=200, verbose_name='problem')),
                ('treatment', models.TextField(max_length=200, verbose_name='treatment')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.IntegerField(default=0, verbose_name='medicine_id')),
                ('medicine', models.CharField(max_length=200, verbose_name='medicine')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('dosage', models.CharField(default='', max_length=200, verbose_name='dosage')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitmanagement.Health')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200, verbose_name='dog_name')),
                ('serial_number', models.CharField(default='#', max_length=200, verbose_name='serial_number')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('veterinary', models.CharField(default='Change this to Foreign Key User', max_length=200, verbose_name='veterinary')),
                ('cage_number', models.IntegerField(default='0', verbose_name='dog')),
                ('general_appearance', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='general_appearance')),
                ('integumentary', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='integumentary')),
                ('musculo_skeletal', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='musculo_skeletal')),
                ('respiratory', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='respiratory')),
                ('genito_urinary', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='genito_urinary')),
                ('nervous', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='nervous')),
                ('circulatory', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='circulatory')),
                ('digestive', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='digestive')),
                ('mucous_membrances', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='mucous_membrances')),
                ('lymph_nodes', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='lymph_nodes')),
                ('eyes', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='eyes')),
                ('ears', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='ears')),
                ('remarks', models.TextField(max_length=200, verbose_name='remarks')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
    ]
