# Generated by Django 2.1.2 on 2018-10-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planningandacquiring', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('problem', models.TextField(max_length=200, verbose_name='problem')),
                ('treatment', models.TextField(max_length=200, verbose_name='treatment')),
                ('status', models.CharField(default='Pending', max_length=200, verbose_name='status')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('dosage', models.CharField(default='', max_length=200, verbose_name='dosage')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitmanagement.Health')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('veterinary', models.CharField(default='Change this to Foreign Key User', max_length=200, verbose_name='veterinary')),
                ('cage_number', models.IntegerField(default='0', verbose_name='dog')),
                ('general_appearance', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='general_appearance')),
                ('integumentary', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='integumentary')),
                ('musculo_skeletal', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='musculo_skeletal')),
                ('respiratory', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='respiratory')),
                ('genito_urinary', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='genito_urinary')),
                ('nervous', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='nervous')),
                ('circulatory', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='circulatory')),
                ('digestive', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='digestive')),
                ('mucous_membrances', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='mucous_membrances')),
                ('lymph_nodes', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='lymph_nodes')),
                ('eyes', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='eyes')),
                ('ears', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Not Examined', 'Not Examined')], max_length=200, verbose_name='ears')),
                ('remarks', models.TextField(max_length=200, verbose_name='remarks')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('BORDETELLA', 'BORDETELLA'), ('CORONAVIRUS', 'CORONAVIRUS'), ('DISTEPER', 'DISTEPER'), ('HEPATITIS', 'HEPATITIS'), ('LEPTOSPIROSIS', 'LEPTOSPIROSIS'), ('LYME', 'LYME'), ('MEASLES', 'MEASLES'), ('PARAINLUENZA', 'PARAINLUENZA'), ('PARVOVIRUS', 'PARVOVIRUS'), ('RABIES', 'RABIES'), ('TRACHEOBRONCHTIS', 'TRACHEOBRONCHTIS')], max_length=200, verbose_name='disease')),
                ('date_vaccinated', models.DateField(auto_now_add=True, verbose_name='date_vaccinated')),
                ('date_validity', models.DateField(blank=True, verbose_name='date_validity')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
    ]
