# Generated by Django 2.1.2 on 2018-10-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0002_auto_20181016_1958'),
        ('inventory', '0002_auto_20181016_1958'),
        ('unitmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('BORDETELLA', 'BORDETELLA'), ('CORONAVIRUS', 'CORONAVIRUS'), ('DISTEPER', 'DISTEPER'), ('HEPATITIS', 'HEPATITIS'), ('LEPTOSPIROSIS', 'LEPTOSPIROSIS'), ('LYME', 'LYME'), ('MEASLES', 'MEASLES'), ('PARAINLUENZA', 'PARAINLUENZA'), ('PARVOVIRUS', 'PARVOVIRUS'), ('RABIES', 'RABIES'), ('TRACHEOBRONCHTIS', 'TRACHEOBRONCHTIS')], max_length=200, verbose_name='disease')),
                ('date_vaccinated', models.DateField(auto_now_add=True, verbose_name='date_vaccinated')),
                ('date_validity', models.DateField(blank=True, verbose_name='date_validity')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.RemoveField(
            model_name='healthmedicine',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='physicalexam',
            name='dog_name',
        ),
        migrations.RemoveField(
            model_name='physicalexam',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='health',
            name='status',
            field=models.CharField(default='Pending', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='healthmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine'),
        ),
    ]
