# Generated by Django 2.1a1 on 2019-02-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('planningandacquiring', '0001_initial'),
        ('profiles', '0001_initial'),
        ('unitmanagement', '0002_auto_20181126_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200, verbose_name='disease')),
                ('date_vaccinated', models.DateField(blank=True, null=True, verbose_name='date_vaccinated')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='date_vaccinated',
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='date_validity',
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccincerecord',
            name='veterinary',
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='anti_rabies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='bordetella_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='bordetella_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='deworming_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='deworming_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='deworming_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='deworming_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='dhppil4_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='dhppil4_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='dhppil_cv_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='dhppil_cv_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='dhppil_cv_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='heartworm_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='k9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9'),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccincerecord',
            name='tick_flea_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccineused',
            name='vaccine_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitmanagement.VaccinceRecord'),
        ),
        migrations.AddField(
            model_name='vaccineused',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User'),
        ),
    ]
