# Generated by Django 2.1a1 on 2019-02-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_vet_supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='total')),
            ],
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='equipment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='equipment_total'),
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='food_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='food_total'),
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='grand_total'),
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='medicine_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='medicine_total'),
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='vaccine_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='vaccine_total'),
        ),
        migrations.AddField(
            model_name='budget_allocation',
            name='vet_supply_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='vet_supply_total'),
        ),
        migrations.AddField(
            model_name='budget_equipment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='budget_food',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='budget_medicine',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='budget_vet_supply',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.Budget_allocation'),
        ),
        migrations.AddField(
            model_name='budget_vet_supply',
            name='vet_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous'),
        ),
        migrations.AddField(
            model_name='budget_vaccine',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.Budget_allocation'),
        ),
        migrations.AddField(
            model_name='budget_vaccine',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine'),
        ),
    ]
