# Generated by Django 2.1.2 on 2018-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='date_from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='date_to')),
            ],
        ),
        migrations.CreateModel(
            name='K9_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('date_bought', models.DateField(blank=True, null=True, verbose_name='date_bought')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.RemoveField(
            model_name='medicine_assignment',
            name='K9',
        ),
        migrations.DeleteModel(
            name='Miscellaneous',
        ),
        migrations.DeleteModel(
            name='Medicine_Assignment',
        ),
    ]
