# Generated by Django 2.1.2 on 2018-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k9',
            name='microchip',
            field=models.CharField(default='Unassigned Microchip', max_length=200, verbose_name='microchip'),
        ),
        migrations.AlterField(
            model_name='k9',
            name='serial_number',
            field=models.CharField(default='Unassigned Serial Number', max_length=200, verbose_name='serial_number'),
        ),
    ]
