# Generated by Django 2.1a1 on 2018-09-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k9',
            name='color',
            field=models.CharField(choices=[('Brown', 'Brown'), ('Black', 'Black'), ('Gray', 'Gray'), ('White', 'White'), ('Yellow', 'Yellow'), ('Mixed', 'Mixed')], default='Unspecified', max_length=200, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='k9',
            name='year_retired',
            field=models.DateField(blank=True, null=True, verbose_name='year_retired'),
        ),
    ]
