# Generated by Django 2.1a1 on 2018-11-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181122_2125'),
        ('profiles', '0002_auto_20181122_2125'),
        ('planningandacquiring', '0002_auto_20181025_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k9_request_forecast', models.IntegerField(default=0, verbose_name='k9_request_forecast')),
                ('k9_needed_for_demand', models.IntegerField(default=0, verbose_name='k9s_needed_for_demand')),
                ('k9_cuurent', models.IntegerField(default=0, verbose_name='k9_current')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
                ('date_tobe_budgeted', models.DateField(verbose_name='date_tobe_budgeted')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.Budget_allocation')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Miscellaneous')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.Budget_allocation')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='price')),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.Budget_allocation')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='k9',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.User'),
        ),
        migrations.AddField(
            model_name='k9',
            name='training_count',
            field=models.IntegerField(default=0, verbose_name='training_count'),
        ),
        migrations.AddField(
            model_name='k9',
            name='training_level',
            field=models.CharField(default='Stage 0', max_length=200, verbose_name='training_level'),
        ),
        migrations.AddField(
            model_name='k9_new_owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='k9_new_owner',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=200, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='k9_past_owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='k9_past_owner',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=200, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='k9_donated',
            name='k9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9'),
        ),
    ]
