# Generated by Django 2.1a1 on 2018-09-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0002_auto_20180927_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k9',
            name='assignment',
            field=models.CharField(default='None', max_length=200, verbose_name='assignment'),
        ),
    ]
