# Generated by Django 2.1a1 on 2019-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0003_auto_20190213_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_food',
            name='food',
            field=models.CharField(default='Adult', max_length=200, verbose_name='food'),
        ),
    ]
