# Generated by Django 2.1a1 on 2019-02-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployment', '0001_initial'),
        ('profiles', '0001_initial'),
        ('planningandacquiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K9_Adopted_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=200, verbose_name='sex')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('contact_no', models.CharField(max_length=200, verbose_name='contact_no')),
                ('date_adopted', models.DateField(auto_now_add=True, verbose_name='date_adopted')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='K9_Genealogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=0, verbose_name='depth')),
                ('f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f', to='planningandacquiring.K9')),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m', to='planningandacquiring.K9')),
                ('o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
                ('zero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zero', to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='K9_Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_area', to='deployment.Location')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to='profiles.User')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='k9', to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='Record_Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_leash', models.BooleanField(default=False)),
                ('off_leash', models.BooleanField(default=False)),
                ('obstacle_course', models.BooleanField(default=False)),
                ('panelling', models.BooleanField(default=False)),
                ('port_plant', models.CharField(default='', max_length=200, verbose_name='port_plant')),
                ('port_find', models.CharField(default='', max_length=200, verbose_name='port_find')),
                ('port_time', models.CharField(default='', max_length=200, verbose_name='port_time')),
                ('building_plant', models.CharField(default='', max_length=200, verbose_name='building_plant')),
                ('building_find', models.CharField(default='', max_length=200, verbose_name='building_find')),
                ('building_time', models.CharField(default='', max_length=200, verbose_name='building_time')),
                ('vehicle_plant', models.CharField(default='', max_length=200, verbose_name='vehicle_plant')),
                ('vehicle_find', models.CharField(default='', max_length=200, verbose_name='vehicle_find')),
                ('vehicle_time', models.CharField(default='', max_length=200, verbose_name='vehicle_time')),
                ('baggage_plant', models.CharField(default='', max_length=200, verbose_name='baggage_plant')),
                ('baggage_find', models.CharField(default='', max_length=200, verbose_name='baggage_find')),
                ('baggage_time', models.CharField(default='', max_length=200, verbose_name='baggage_time')),
                ('others_plant', models.CharField(default='', max_length=200, verbose_name='others_plant')),
                ('others_find', models.CharField(default='', max_length=200, verbose_name='others_find')),
                ('others_time', models.CharField(default='', max_length=200, verbose_name='others_time')),
                ('daily_rating', models.CharField(default='', max_length=200, verbose_name='daily_rating')),
                ('MARSEC', models.BooleanField(default=False)),
                ('MARLEN', models.BooleanField(default=False)),
                ('MARSAR', models.BooleanField(default=False)),
                ('MAREP', models.BooleanField(default=False)),
                ('morning_feed', models.CharField(default='', max_length=200, verbose_name='morning_feed')),
                ('evening_feed', models.CharField(default='', max_length=200, verbose_name='evening_feed')),
                ('date_today', models.DateField(auto_now_add=True, verbose_name='date_today')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
                ('k9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(default='None', max_length=50, verbose_name='training')),
                ('stage', models.CharField(default='Stage 0', max_length=200, verbose_name='stage')),
                ('stage1_1', models.BooleanField(default=False)),
                ('stage1_2', models.BooleanField(default=False)),
                ('stage1_3', models.BooleanField(default=False)),
                ('stage2_1', models.BooleanField(default=False)),
                ('stage2_2', models.BooleanField(default=False)),
                ('stage2_3', models.BooleanField(default=False)),
                ('stage3_1', models.BooleanField(default=False)),
                ('stage3_2', models.BooleanField(default=False)),
                ('stage3_3', models.BooleanField(default=False)),
                ('grade', models.CharField(default='No Grade Yet', max_length=50, verbose_name='grade')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
    ]
