# Generated by Django 2.1a1 on 2018-11-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planningandacquiring', '0003_auto_20181122_2125'),
        ('deployment', '0004_auto_20181122_2125'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K9_Adopted_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=200, verbose_name='sex')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('contact_no', models.CharField(max_length=200, verbose_name='contact_no')),
                ('date_adopted', models.DateField(auto_now_add=True, verbose_name='date_adopted')),
                ('k9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(default='None', max_length=50, verbose_name='training')),
                ('stage', models.CharField(default='Stage 0', max_length=200, verbose_name='stage')),
                ('stage1_1', models.BooleanField(default=False)),
                ('stage1_2', models.BooleanField(default=False)),
                ('stage1_3', models.BooleanField(default=False)),
                ('stage2_1', models.BooleanField(default=False)),
                ('stage2_2', models.BooleanField(default=False)),
                ('stage2_3', models.BooleanField(default=False)),
                ('stage3_1', models.BooleanField(default=False)),
                ('stage3_2', models.BooleanField(default=False)),
                ('stage3_3', models.BooleanField(default=False)),
                ('grade', models.CharField(default='No Grade Yet', max_length=50, verbose_name='grade')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks')),
                ('k9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planningandacquiring.K9')),
            ],
        ),
        migrations.AddField(
            model_name='k9_handler',
            name='deployment_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_area', to='deployment.Location'),
        ),
    ]
